### ISSUE TITLE
Should we reword the bit about temporary or permanent removal of someone from a community?

### ISSUE THREAD

**Issue by davidcelis** [EthicalSource/contributor_covenant#229]
Hey, Coraline! First off, a huge thanks from me and many others for what you've done with the Contributor Covenant. IMO, you're a hero. I've involved myself in a number of conversations on the adoption of this CoC for open source projects, the latest being Ruby. I am very much in favor of this code of conduct being adopted in more communities. The opposition to this CoC gets really crazy, and a lot of trolls involve themselves, but my experiences I think have pinpointed one bit that's singled out a lot by said opposition, and that's the possibility of temporary or permanent removal from a community.

A lot of the fear mongering with regards to the CoC comes down to people thinking that bans are excessive and worrying that people will get banned willy-nilly. Removal from the community is definitely something that should be a possibility when someone in that community is engaging in harassment. However, I do wonder if the code of conduct could be worded differently to point out that action as being a sort of last resort. It's tricky, because the CoC does already state that issues will be dealt with according to circumstances, but maybe it's too vague? At this point I guess I'm just spitballing.

My main two thoughts with regards to this concern come down to the potential of noting that banning is a last resort, and that a temporary removal is also a possibility. The phrase "temporary removal" appears, but maybe doesn't really sink in. People seem not to understand that there is the option of people returning to the community based on their actions after whatever incident they are involved in. I think they gloss over it because, right next to that, is "permanent ban".

Anyway, I'm curious as to what your thoughts here are. I'd like to be of help in whittling away peoples' concerns with adopting the Contributor Code of Conduct. I think this project has, by far, the best momentum of its kind. Thanks again.

**Comment by phedinkus** [comment]
I'd also like to say I'd love to see more talk about making amends in some way. What path can a person take to correct mistakes they might make? Some situations aren't always so black and white and I'm sure people get nervous they might make a mistake that will cause them to be banned. It seems super scary.

**Comment by parkr** [comment]
> What path can a person take to correct mistakes they might make?

Yeah, I was a bit of confused about whether I should take the concerns to the accused and ask them to explain themselves first? Do they have a "right to face accuser" or "right to defend themselves"?

**Comment by jart** [comment]
Whether or not the accused has the right to face the accuser, or is entitled to due process, are all very important questions.

Thankfully enough, there exists another code of conduct that was put in place on other projects many years ago. It's been battle tested. Many arguments have been resolved over its meaning. And most people accept its contents, or at the very least, follow it. That code of conduct is called the law. And in the anglosphere it dates back many centuries to writing of the Magna Carta.

Projects wishing to ameliorate the concerns David has raised would be well-advised to consider adopting the FTFL-COC as defined by this document: https://gist.github.com/jart/f274d8dc156811a46b22

**Comment by mprelude** [comment]
@jart When we step into shared spaces and collaborative spaces, we often face scenarios where what is legal is not necessarily appropriate in that context. For example, it is legal for me to use expletives, but doing so in a theatre or a school is likely to get me removed.

Aside from that, the legal minimums vary wildly from nation to nation. What is legal in your country may not be legal in mine, so 'the law' is certainly not going to provide a baseline of acceptability in any international project.

The purpose of a Code of Conduct is not to 'reinvent' the law, but to build upon those basic expectations in order to foster a more welcoming environment. Whether a specific CoC gets the balance right is a worthwhile discussion, but creating an expected minimum standard of behaviour above 'follow the law' is certainly not revolutionary.

Just my $0.02, and certainly doesn't amount to absolute support for any specific implementation of a CoC.

**Comment by igraves** [comment]
@davidcelis I think the part of the CoC you're referring to makes explicit the powers of project maintainers that everyone already knew that they had.  That is to say, if you troll the heck out of any project, you're gonna get thrown out.  The CoC is a covenant (hence the name) wherein maintainers _further_ make explicit their intent to use their powers to further prevent the behavior defined in the document.  The responsibility ultimately rests with maintainers to identify infractions, respond to them, and come to a resolution in a way that fits their community and the CoC.  I think that it's a bit of FUD that promotes the idea that the CoC is the first and last stop for marginalizing some group of people and kicking them out of the project for not engaging in some kind of groupthink.

As far as penalties and bans go, I think this process is something that is best defined by an adopting community of the CoC.  Processes where significant offenders rehabilitate and are brought back into the fold are complicated and expensive.  Communities have limited resources and time.  I think it follows that communities that want to employ procedure in this area need to figure out what works for them and implement it themselves (and add it to their fork of the CoC).  It's hard to identify a good one-size-fits all approach a priori, but it may be possible that a successful process can be derived from many different communities in the future.

**Comment by CoralineAda** [comment]
@igraves That's definitely in the spirit of my intentions.

**Comment by Rudd-O** [comment]
As much as it pains me to say this, I have to agree with @jart here.  The law is the code of conduct.  If you disagree with the law, then vote, campaign, follow the process you were told since little you sat down in civics class. 

Imposing your own law on other people is just going to end up in you having to fight the law.  You know who is going to win that fight.  So, instead of trying to manipulate and wrangle people into your own law, why not just either obey or follow *the law*?

That's all.

**Comment by CoralineAda** [comment]
The law does little to promote civility and fairness and is not a sufficient model for a social structure. For example, things that are not against the law in the US: racism, sexism, homophobia, transphobia, abusive words, harassment (sexual and otherwise). States are trying to take away my right to pee in the right restroom, do you really think politicians would care about someone deliberately misgendering me and otherwise harassing me on GH?

A code of conduct is not like a law. It is a statement of guiding principles and expectations for the behavior of a productive member of a community. It includes examples of positive and negative behavior. It outlines a process for dealing with violations of reasonable expectations for behavior. It is a covenant between project maintainers and project participants. I don’t know why this is so very controversial.

**Comment by jart** [comment]
Hey @CoralineAda could you please link to the GitHub Issue comment where someone was deliberately misgendering you? I ask because you look like a normal woman to me.

> It includes examples of positive and negative behavior.

On what philosophical grounds are you able to define behaviors as positive or negative? Such terminology implies the existence of an objective morality. Would you argue that the examples of positive and negative behavior given by the CC are objectively correct?

If you do not believe they are objective, then do you believe they are culturally relative? If so, *whose* culture is being used to define these behaviors as positive or negative?

**Comment by CoralineAda** [comment]
> On what philosophical grounds are you able to define behaviors as positive or negative? Such terminology implies the existence of an objective morality. Would you argue that the examples of positive and negative behavior given by the CC are objectively correct?
> If you do not believe they are objective, then do you believe they are culturally relative? If so, whose culture is being used to define these behaviors as positive or negative?
> 
Inherent in the formation of communities is the establishment of a common understanding of positive (acceptable) and negative (unacceptable) behaviors. This is necessarily subjective. However, beyond these community-defined standards, there are identifiable, behavioral anti-patterns (such as sexual harassment) that reinforce systemic abuse of certain populations. Some of these are specifically called out and addressed in the CC. The underlying assumption is that a healthy, positive software community aspires to address– or at least not be complicit with– systemic patterns of abuse or discrimination, instead committing to being welcoming and encouraging diversity.

If a given project owner disagrees with this sentiment, does not believe in institutional or widespread social injustice, does not particularly care about creating and managing a welcoming and diverse community, or finds his or her values not aligned with those stated explicitly or implicitly in the CC then they shouldn’t adopt it. They should, however, make the guiding principles of community development and management that they DO believe in EXPLICIT so that would-be participants can make informed decisions about joining a particular community.

I don’t see a thing that is controversial about this.

**Comment by davidcelis** [comment]
@jart, @Rudd-O: Please stop hijacking my issue. I didn't open this conversation to discuss whether or not the Contributor Covenant's Code of Conduct should be a thing. I opened it to discuss a nuance in the wording. If you have something else to discuss, you're free to open a separate issue and start a new conversation. But please stop doing it here.

**Comment by jart** [comment]
Hmm even the men who are most fervently in favor of things like Code of Conducts will still find it their hearts to silence an uppity woman. I'll bother ye no further if I'm not welcome here. Good day sir.

**Comment by davidcelis** [comment]
Yes, because suggesting starting a new conversation as opposed to hijacking this one is definitely silencing.

**Comment by einhverfr** [comment]
One of the difficulties here which I don't think gets the attention it needs is the fact that open source projects do span large cultural gaps and this includes family structures, places where people retire with the kids, and so forth.  These things lead to different views on things like sexuality.  A community which is welcome to all has to recognize that it exists relative to the cultural communities of the participants.  The goal cannot be a globalization of culture war, but rather a cultural peace.

Certain things are culturally relative.  If gender is culturally constructed, then concepts of gender are culturally relative and people should not be excluded because of views here.

Some things are culturally relative and successful projects tend to be tolerant and welcoming across these issues.

I don't know of any open source community that wants an ideological orthodoxy on hot button issues, but for those that do, explicit notice of such is appreciated.

**Comment by einhverfr** [comment]
Consequently I think any responsible maintainer of an open source project is going to be very cautious about enforcing any ideological views on non-project channels, even if those may come across as racist, homophobic, transphobic, etc.

Much of the fear comes from the question of whether the code of conduct is a tool which will create more strife than it prevents.  And if one uses it to try to position a community relative to culture war topics, that is what will happen.

**Comment by einhverfr** [comment]
Question and an honest one:  Is the intent to try to tell the most of the world which has different values that if they express their views on, say, homosexuality on Twitter, that they should not participate in open source?

**Comment by CoralineAda** [comment]
It’s pretty clear with 1.4 what the scope of restrictions and the applicability of the rules are, Chris. You should read it if you haven’t already. Nothing in CC says that someone’s stated opinions affect their participation in the project unless those statements are made within the context of the project.

**Comment by CoralineAda** [comment]
You can have opinions on, say, homosexuality and not express them in homophobic ways to someone who is LGB. This is about conduct and communication, not ideology.

**Comment by Rudd-O** [comment]
@davidcelis nothing is "hijacked" by anyone.  Moreover, the issue doesn't "belong to you" -- your voice matters as much as anyone else's and you have no special privilege or gold star that crowns you king of what is allowable.  You're not a duke, a king, or an earl -- you're just another Github contributor like everyone else, and your voice deserves as much respect and time from everyone else as any one else's voice.  Not more, and certainly not to the extent to demand (however politely) that others shut up.

**Comment by CoralineAda** [comment]
I think that David’s point (forgive me if I am wrong, David) is that this particular Github issue has nothing to do with the conversation that has become attached to it. It’s a fact that the thread has diverged and the conversation should probably be redirected.

**Comment by davidcelis** [comment]
That's all I'm trying to get at. I'm trying to discuss a very specific issue here. I don't a problem with the conversation at hand happening, but I'd prefer it happen in a separate issue. They're open, so anybody here can open another one to discuss this other topic. It's just easier. Thanks!

**Comment by camerons** [comment]
I agree with the sentiment of @davidcelis. A CoC which focuses on highlighting and exposing wrong doing will lead to flash points where defendants feel attacked and are likely to come out fighting in order to defend themselves. I believe such flash points can be significantly mitigated by using supportive instead of dictatorial language. It provides the opportunity for the person being accused to gracefully acknowledge a mistake with their reputation intact.

Source text from the Contributor Covenant:

> Enforcement
> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.
> 
> Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project’s leadership. 

Less confrontation words which convey the same meaning from the [Open Source Geospatial Foundation Code of Conduct](http://www.osgeo.org/code_of_conduct/) (derived from the [Apache Foundation Code of Conduct](https://www.apache.org/foundation/policies/conduct.html))

> Reporting Guidelines
> If you believe someone is breaking this code of conduct, you may reply to them, and point to this code of conduct. Such messages may be in public or in private, whatever is most appropriate. Assume good faith; it is more likely that participants are unaware of their bad behaviour than that they intentionally try to degrade the quality of the discussion. Should there be difficulties in dealing with the situation, you may report your concerns to event staff, a forum leader or the OSGeo Board. Serious or persistent offenders may be expelled from the event or forum by event organizers or forum leaders.

**Comment by Loky1s** [comment]
Yes, because you could have someone removed that you don't like or someone that you have taken something from them because of what you say they said or what you say.They've done so that really needs to be looked into a little deeper than what you're looking into it.Cause that's the problem.With what's going on now?Nobody's taking ownership for what you're doing wrong.They're passing it off onto another person

**Comment by einhverfr** [comment]
> You can have opinions on, say, homosexuality and not express them in homophobic ways to someone who is LGB. This is about conduct and communication, not ideology.
> 
> > On Feb 11, 2016, at 6:05 AM, Chris Travers [notifications@github.com](mailto:notifications@github.com) wrote:
> > Question and an honest one: Is the intent to try to tell the most of the world which has different values that if they express their views on, say, homosexuality on Twitter, that they should not participate in open source?
> > —
> > Reply to this email directly or view it on GitHub [#229 (comment)](https://github.com/EthicalSource/contributor_covenant/issues/229#issuecomment-182828305).

But things like the proper form of marriage, limitations on family structures, function of family in relation to children and elsers, etc are deeply cultural.

I would not want to have a code of conduct in any project I work with which effectively picks culture wars by what amount to white Western countries against post-colonial people-of-color-majority cultures.

As someone who is now living (as a guest effectively) in a Global South country, it just isn't my place as an open source contributor to push my politics on their countries.

**Comment by Rudd-O** [comment]
Hah.  Eight years have passed, and my suspicions were proven correct.  I think most of us have figured out — by the extensive adoption of this (or variants thereof) — that the point of the verbiage in this covenant was to enable cultural hegemons to impose their culture and mores on others, and to defenestrate anyone who resists out of open source projects.

I want to urge anyone still considering a "code of conduct" for their project to look into what the Ladybird browser did:

https://github.com/LadybirdBrowser/ladybird/blob/master/CODE_OF_CONDUCT.md

**Comment by Chealer** [comment]
> […]
> 
> Source text from the Contributor Covenant:
> 
> > Enforcement
> > Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.
> > Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project’s leadership.
> 
> Less confrontation words which convey the same meaning from the [Open Source Geospatial Foundation Code of Conduct](http://www.osgeo.org/code_of_conduct/) (derived from the [Apache Foundation Code of Conduct](https://www.apache.org/foundation/policies/conduct.html))
> […]

Thanks @camerons 
This section is a lot better as of version 2.1:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [INSERT CONTACT METHOD]. All complaints will be reviewed and investigated promptly and fairly.
> 
> All community leaders are obligated to respect the privacy and security of the reporter of any incident.

(although "respecting the security of the reporter" is surely awkward)

**Comment by Chealer** [comment]
In reply to @igraves : 
> As far as penalties and bans go, I think this process is something that is best defined by an adopting community of the CoC. Processes where significant offenders rehabilitate and are brought back into the fold are complicated and expensive (but they can be worth it, too!). Communities have limited resources and time. I think it follows that communities that want to employ procedure in this area need to figure out what works for them and implement it themselves (and add it to their fork of the CoC). It's hard to identify a good one-size-fits-all approach a priori, but it may be possible that a successful process can be derived from many different communities in the future.

Right. Myself and others have pointed out limitations of the contents about enforcement in ticket #910, which suggests to split it (at least partly) out of the CoC.

I agree with @davidcelis; coming from a project which claims to support openness and inclusiveness, it is surprising to see the document promoting temporary or even permanent bans.
